export const dummyBooks = [
  {
    id: "1",
    title: "The Midnight Library",
    author: "Matt Haig",
    publisher: "Viking",
    description:
      "Between life and death there is a library, and within that library, the shelves go on forever. Every book provides a chance to try another life you could have lived. To see how things would be if you had made other choices... Would you have done anything different, if you had the chance to undo your regrets?",
    condition: "Like New",
    status: "Available",
    genre: "Fiction",
    language: "English",
    location: {
      lat: 40.7128,
      lng: -74.006,
      address: "123 Broadway, New York",
    },
    coverImage: "/placeholder.svg?height=300&width=200&text=Midnight+Library",
    listedDate: "2023-10-15T14:30:00Z",
  },
  {
    id: "2",
    title: "Educated",
    author: "Tara Westover",
    publisher: "Random House",
    description:
      "An unforgettable memoir about a young girl who, kept out of school, leaves her survivalist family and goes on to earn a PhD from Cambridge University. A coming-of-age story that gets to the heart of what an education is and what it offers: the perspective to see one's life through new eyes.",
    condition: "Good",
    status: "Available",
    genre: "Memoir",
    language: "English",
    location: {
      lat: 40.7282,
      lng: -73.9942,
      address: "45 Park Avenue, New York",
    },
    coverImage: "/placeholder.svg?height=300&width=200&text=Educated",
    listedDate: "2023-09-22T09:15:00Z",
  },
  {
    id: "3",
    title: "Sapiens: A Brief History of Humankind",
    author: "Yuval Noah Harari",
    publisher: "Harper",
    description:
      "A groundbreaking narrative of humanity's creation and evolution that explores the ways in which biology and history have defined us and enhanced our understanding of what it means to be 'human.'",
    condition: "Very Good",
    status: "Available",
    genre: "Non-Fiction",
    language: "English",
    location: {
      lat: 40.7112,
      lng: -74.0123,
      address: "78 Wall Street, New York",
    },
    coverImage: "/placeholder.svg?height=300&width=200&text=Sapiens",
    listedDate: "2023-10-05T16:45:00Z",
  },
  {
    id: "4",
    title: "The Silent Patient",
    author: "Alex Michaelides",
    publisher: "Celadon Books",
    description:
      "Alicia Berenson's life is seemingly perfect. A famous painter married to an in-demand fashion photographer, she lives in a grand house with big windows overlooking a park in one of London's most desirable areas. One evening her husband Gabriel returns home late from a fashion shoot, and Alicia shoots him five times in the face, and then never speaks another word.",
    condition: "New",
    status: "Reserved",
    genre: "Mystery",
    language: "English",
    location: {
      lat: 40.7589,
      lng: -73.9851,
      address: "210 5th Avenue, New York",
    },
    coverImage: "/placeholder.svg?height=300&width=200&text=Silent+Patient",
    listedDate: "2023-11-01T10:30:00Z",
  },
  {
    id: "5",
    title: "Atomic Habits",
    author: "James Clear",
    publisher: "Avery",
    description:
      "No matter your goals, Atomic Habits offers a proven framework for improving--every day. James Clear, one of the world's leading experts on habit formation, reveals practical strategies that will teach you exactly how to form good habits, break bad ones, and master the tiny behaviors that lead to remarkable results.",
    condition: "Good",
    status: "Available",
    genre: "Self-Help",
    language: "English",
    location: {
      lat: 40.7421,
      lng: -73.9911,
      address: "33 Madison Avenue, New York",
    },
    coverImage: "/placeholder.svg?height=300&width=200&text=Atomic+Habits",
    listedDate: "2023-10-18T13:20:00Z",
  },
  {
    id: "6",
    title: "The Alchemist",
    author: "Paulo Coelho",
    publisher: "HarperOne",
    description:
      "Paulo Coelho's masterpiece tells the mystical story of Santiago, an Andalusian shepherd boy who yearns to travel in search of a worldly treasure. His quest will lead him to riches far different—and far more satisfying—than he ever imagined.",
    condition: "Acceptable",
    status: "Available",
    genre: "Fiction",
    language: "Spanish",
    location: {
      lat: 40.7339,
      lng: -74.0021,
      address: "15 Greenwich Avenue, New York",
    },
    coverImage: "/placeholder.svg?height=300&width=200&text=The+Alchemist",
    listedDate: "2023-09-10T11:45:00Z",
  },
  {
    id: "7",
    title: "Becoming",
    author: "Michelle Obama",
    publisher: "Crown",
    description:
      "In her memoir, a work of deep reflection and mesmerizing storytelling, Michelle Obama invites readers into her world, chronicling the experiences that have shaped her—from her childhood on the South Side of Chicago to her years as an executive balancing the demands of motherhood and work.",
    condition: "Like New",
    status: "Available",
    genre: "Biography",
    language: "English",
    location: {
      lat: 40.7831,
      lng: -73.9712,
      address: "86 Central Park West, New York",
    },
    coverImage: "/placeholder.svg?height=300&width=200&text=Becoming",
    listedDate: "2023-11-05T15:10:00Z",
  },
  {
    id: "8",
    title: "Dune",
    author: "Frank Herbert",
    publisher: "Ace",
    description:
      'Set on the desert planet Arrakis, Dune is the story of the boy Paul Atreides, heir to a noble family tasked with ruling an inhospitable world where the only thing of value is the "spice" melange, a drug capable of extending life and enhancing consciousness.',
    condition: "Good",
    status: "Available",
    genre: "Science Fiction",
    language: "English",
    location: {
      lat: 40.7614,
      lng: -73.9776,
      address: "120 East 59th Street, New York",
    },
    coverImage: "/placeholder.svg?height=300&width=200&text=Dune",
    listedDate: "2023-10-25T09:30:00Z",
  },
  {
    id: "9",
    title: "The Great Gatsby",
    author: "F. Scott Fitzgerald",
    publisher: "Scribner",
    description:
      "The Great Gatsby, F. Scott Fitzgerald's third book, stands as the supreme achievement of his career. This exemplary novel of the Jazz Age has been acclaimed by generations of readers. The story is of the fabulously wealthy Jay Gatsby and his new love for the beautiful Daisy Buchanan.",
    condition: "Very Good",
    status: "Reserved",
    genre: "Classic",
    language: "English",
    location: {
      lat: 40.7192,
      lng: -74.0121,
      address: "55 Liberty Street, New York",
    },
    coverImage: "/placeholder.svg?height=300&width=200&text=Great+Gatsby",
    listedDate: "2023-09-18T14:20:00Z",
  },
  {
    id: "10",
    title: "The Hobbit",
    author: "J.R.R. Tolkien",
    publisher: "Houghton Mifflin Harcourt",
    description:
      "Bilbo Baggins is a hobbit who enjoys a comfortable, unambitious life, rarely traveling any farther than his pantry or cellar. But his contentment is disturbed when the wizard Gandalf and a company of dwarves arrive on his doorstep one day to whisk him away on an adventure.",
    condition: "Good",
    status: "Available",
    genre: "Fantasy",
    language: "English",
    location: {
      lat: 40.7501,
      lng: -73.9929,
      address: "350 5th Avenue, New York",
    },
    coverImage: "/placeholder.svg?height=300&width=200&text=The+Hobbit",
    listedDate: "2023-10-30T12:15:00Z",
  },
  {
    id: "11",
    title: "To Kill a Mockingbird",
    author: "Harper Lee",
    publisher: "HarperCollins",
    description:
      "The unforgettable novel of a childhood in a sleepy Southern town and the crisis of conscience that rocked it. 'To Kill A Mockingbird' became both an instant bestseller and a critical success when it was first published in 1960. It went on to win the Pulitzer Prize in 1961 and was later made into an Academy Award-winning film.",
    condition: "Acceptable",
    status: "Available",
    genre: "Classic",
    language: "English",
    location: {
      lat: 40.7223,
      lng: -73.9874,
      address: "25 Cooper Square, New York",
    },
    coverImage: "/placeholder.svg?height=300&width=200&text=Mockingbird",
    listedDate: "2023-09-05T10:45:00Z",
  },
  {
    id: "12",
    title: "1984",
    author: "George Orwell",
    publisher: "Signet Classic",
    description:
      "Among the seminal texts of the 20th century, Nineteen Eighty-Four is a rare work that grows more haunting as its futuristic purgatory becomes more real. Published in 1949, the book offers political satirist George Orwell's nightmarish vision of a totalitarian, bureaucratic world and one poor stiff's attempt to find individuality.",
    condition: "Good",
    status: "Available",
    genre: "Dystopian",
    language: "English",
    location: {
      lat: 40.7484,
      lng: -73.9857,
      address: "11 West 32nd Street, New York",
    },
    coverImage: "/placeholder.svg?height=300&width=200&text=1984",
    listedDate: "2023-10-12T16:30:00Z",
  },
]

// User's own books for the trade feature
export const userBooks = [
  {
    id: "u1",
    title: "The Catcher in the Rye",
    author: "J.D. Salinger",
    publisher: "Little, Brown and Company",
    description:
      "The hero-narrator of The Catcher in the Rye is an ancient child of sixteen, a native New Yorker named Holden Caulfield. Through circumstances that tend to preclude adult, secondhand description, he leaves his prep school in Pennsylvania and goes underground in New York City for three days.",
    condition: "Good",
    status: "Available",
    genre: "Classic",
    language: "English",
    location: {
      lat: 40.7128,
      lng: -74.006,
      address: "Your Location",
    },
    coverImage: "/placeholder.svg?height=300&width=200&text=Catcher+in+the+Rye",
    listedDate: "2023-10-01T09:00:00Z",
  },
  {
    id: "u2",
    title: "Pride and Prejudice",
    author: "Jane Austen",
    publisher: "Penguin Classics",
    description:
      "Since its immediate success in 1813, Pride and Prejudice has remained one of the most popular novels in the English language. Jane Austen called this brilliant work 'her own darling child' and its vivacious heroine, Elizabeth Bennet, 'as delightful a creature as ever appeared in print.'",
    condition: "Very Good",
    status: "Available",
    genre: "Classic",
    language: "English",
    location: {
      lat: 40.7128,
      lng: -74.006,
      address: "Your Location",
    },
    coverImage: "/placeholder.svg?height=300&width=200&text=Pride+and+Prejudice",
    listedDate: "2023-09-15T14:30:00Z",
  },
  {
    id: "u3",
    title: "The Lord of the Rings",
    author: "J.R.R. Tolkien",
    publisher: "Mariner Books",
    description:
      "One Ring to rule them all, One Ring to find them, One Ring to bring them all and in the darkness bind them. In ancient times the Rings of Power were crafted by the Elven-smiths, and Sauron, the Dark Lord, forged the One Ring, filling it with his own power so that he could rule all others.",
    condition: "Like New",
    status: "Available",
    genre: "Fantasy",
    language: "English",
    location: {
      lat: 40.7128,
      lng: -74.006,
      address: "Your Location",
    },
    coverImage: "/placeholder.svg?height=300&width=200&text=Lord+of+the+Rings",
    listedDate: "2023-10-20T11:45:00Z",
  },
]

